/*
 * This source file was generated by the Gradle 'init' task
 */
package org.babu1993;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SigSwitchTest {
    @Test
    void testSigSwitchInitialization() {
        try {
            SigSwitch sigSwitch = new SigSwitch();
            assertNotNull(sigSwitch, "SigSwitch instance should not be null");
        } catch (Throwable t) {
            fail("Initialization of SigSwitch threw an exception: " + t.getMessage());
        }
    }

    @Test
    void testRegisterHandlerWithInvalidSignal() {
        try {
            SigSwitch sigSwitch = new SigSwitch();
            assertThrows(IllegalArgumentException.class, () -> {
                sigSwitch.registerHandler(31, signal -> System.out.println("Signal received: " + signal));
            }, "Expected IllegalArgumentException for signal value less than 32");
        } catch (Throwable t) {
            fail("Initialization of SigSwitch threw an exception: " + t.getMessage());
        }
    }
}
