/*
 * This source file was generated by the Gradle 'init' task
 */
package org.babu1993;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledOnOs;
import org.junit.jupiter.api.condition.OS;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@EnabledOnOs(OS.LINUX)
class SigSwitchTest {

    static class AnnotatedHandler {
        @SignalHandler
        public void handle(int signal) {}
    }

    private SigSwitch sigSwitch;

    @BeforeEach
    void setUp() {
        assertDoesNotThrow(() -> sigSwitch = new SigSwitch(),
                "SigSwitch constructor should not throw on Linux");
    }

    @AfterEach
    void tearDown() {
        sigSwitch.close();
    }

    @Test
    void testSigSwitchInitialization() {
        assertNotNull(sigSwitch, "SigSwitch instance should not be null");
    }

    @Test
    void testRegisterHandlerReturnsSignalInfo() throws Exception {
        SignalHandlerInfo info = sigSwitch.registerHandler((SigSwitchHandler) signal -> {});
        assertNotNull(info, "registerHandler should return a non-null SignalHandlerInfo");
    }

    @Test
    void testRegisterHandlerAssignsSignalInValidRange() throws Exception {
        SignalHandlerInfo info = sigSwitch.registerHandler((SigSwitchHandler) signal -> {});
        assertTrue(info.signal() >= 36 && info.signal() <= 64,
                "Auto-assigned signal should be in range 36-64, got: " + info.signal());
    }

    @Test
    void testRegisterMultipleHandlersGetDifferentSignals() throws Exception {
        SignalHandlerInfo info1 = sigSwitch.registerHandler((SigSwitchHandler) signal -> {});
        SignalHandlerInfo info2 = sigSwitch.registerHandler((SigSwitchHandler) signal -> {});
        assertNotEquals(info1.signal(), info2.signal(), "Each handler should be assigned a unique signal");
    }

    @Test
    void testUnregisterHandlerDoesNotThrow() throws Exception {
        SignalHandlerInfo info = sigSwitch.registerHandler((SigSwitchHandler) signal -> {});
        assertDoesNotThrow(() -> sigSwitch.unregisterHandler(info.signal()),
                "unregisterHandler should not throw for a registered signal");
    }

    @Test
    void testUnregisterNonRegisteredSignalDoesNotThrow() {
        // unregisterHandler is a no-op for unregistered signals
        assertDoesNotThrow(() -> sigSwitch.unregisterHandler(36));
    }

    @Test
    void testRegisterHandlerWithAnnotatedObject() throws Exception {
        List<SignalHandlerInfo> infos = sigSwitch.registerHandler(new AnnotatedHandler());
        assertEquals(1, infos.size(), "One @SignalHandler method should produce one registered handler");
    }

    @Test
    void testRegisterHandlerWithNoAnnotatedMethodsReturnsEmptyList() throws Exception {
        List<SignalHandlerInfo> infos = sigSwitch.registerHandler(new Object());
        assertTrue(infos.isEmpty(), "Object with no @SignalHandler methods should register nothing");
    }
}
